services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:G9W38EdRXIJtdAXKKpVB@3.111.55.59:54325/osdb1
      - REDIS_HOST=online-saathi-osdbr-xenn16
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=yUOn9G8gMuEJEDkcYXmq
      - REDIS_URL=redis://default:yUOn9G8gMuEJEDkcYXmq@online-saathi-osdbr-xenn16:6379
      - JWT_SECRET=12345
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=darpanpatel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=saathi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U darpanpatel -d saathi" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
